version: '3'
services:

   satomempool:
     build: .
     image: satomempool:rdbc-v4
     volumes:
       - ./conf:/data/conf:ro
     labels:
       - "name=satomempool"
     restart: always
     logging:
       driver: "json-file"
       options:
         labels: "name"
         max-size: "1g"
         max-file: "3"
